### ISSUE TITLE
GoLang 有国内官方镜像

### ISSUE THREAD

**Issue by ZeroAurora** [LanceLRQ/helang-go#1]
https://github.com/LanceLRQ/helang-go/blob/1ad813d7d600c56bc27c4ccec67dd611cb025c0f/README.md?plain=1#L25

https://golang.google.cn/dl/

在原仓库看到了就来支持一下，非常好工作 :heart:

**Comment by LanceLRQ** [comment]
感谢分享！已更新！❤️
